services:
  kilo-storage:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - kilo-storage:/var/lib/kilo
    environment:
      - KILO_SERVICE_TYPE=STORAGE
      - KILO_DATA_DIR=/var/lib/kilo
      - KILO_STORAGE_SERVICE_URL=http://kilo-storage:8080

  kilo-metadata:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - kilo-metadata:/var/lib/kilo
    environment:
      - KILO_SERVICE_TYPE=METADATA
      - KILO_DATA_DIR=/var/lib/kilo
      - KILO_STORAGE_SERVICE_URL=http://kilo-storage:8080
    
  
volumes:
  kilo-storage:
    driver: local
  kilo-metadata:
    driver: local